### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by bd0bd** [backdrop-contrib/r4032login#1]
Cannot install on Backdrop 1.7.0

Error installing Redirect 403 to User Login. Cannot extract temporary://update-cache-03a5c401/1.x-1.0.1, not a valid archive.

**Comment by deekayen** [comment]
I'm not really sure what to do with this since it's not code related. I tried downloading the zip file and un-archived it with the built-in Mac archive utility and got no complaints.

Have you tried downloading again? Maybe the download just didn't finish the first time?

**Comment by bd0bd** [comment]
Hi!
I do not un-archive it on my side.
I install it via Backdrop autoinstaller.

**Comment by deekayen** [comment]
Is this the only module that fails?

**Comment by bd0bd** [comment]
Yes.
BD 1.7.0

But I can not try it again now.
Because I have deleted all Backdrop websites databases - too much problems with Backdrop at many cases.
Drupal is more stable and reliable ...

**Comment by bd0bd** [comment]
BD clean installed today and the module installation problem exist:

![img_20170605_070519](https://cloud.githubusercontent.com/assets/13515302/26770220/6eeeb1c4-49bd-11e7-8edf-ff40debc9f94.JPG)

**Comment by bd0bd** [comment]
Please look https://github.com/backdrop-contrib/block_refresh/issues/1

**Comment by deekayen** [comment]
I don't see what that issue has to do with this one, but I guess I could try making a silly change as an excuse to generate a new install zip.

**Comment by deekayen** [comment]
I released 1.x-1.0.2 as an excuse to generate a new zip file since you're getting an invalid archive error.

**Comment by bd0bd** [comment]
It is ok now. Thank you!
